[package]
name = "openxrnative"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = "0.33"
vulkano-shaders = "0.33"
vulkano-win = "0.33"
winit = "0.28"
cgmath = "0.18"
bytemuck = { version = "1.13", features = ["derive"] }
